# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: another_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='another_service.proto',
  package='',
  serialized_pb='\n\x15\x61nother_service.proto\"\'\n\x10PBAnotherRequest\x12\x13\n\x0brequest_str\x18\x01 \x02(\t\")\n\x11PBAnotherResponse\x12\x14\n\x0cresponse_str\x18\x01 \x02(\t')




_PBANOTHERREQUEST = _descriptor.Descriptor(
  name='PBAnotherRequest',
  full_name='PBAnotherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_str', full_name='PBAnotherRequest.request_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=64,
)


_PBANOTHERRESPONSE = _descriptor.Descriptor(
  name='PBAnotherResponse',
  full_name='PBAnotherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_str', full_name='PBAnotherResponse.response_str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['PBAnotherRequest'] = _PBANOTHERREQUEST
DESCRIPTOR.message_types_by_name['PBAnotherResponse'] = _PBANOTHERRESPONSE

class PBAnotherRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBANOTHERREQUEST

  # @@protoc_insertion_point(class_scope:PBAnotherRequest)

class PBAnotherResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBANOTHERRESPONSE

  # @@protoc_insertion_point(class_scope:PBAnotherResponse)


# @@protoc_insertion_point(module_scope)
