# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_service.proto',
  package='',
  serialized_pb='\n\x14simple_service.proto\"!\n\x0fPBSimpleRequest\x12\x0e\n\x06youpla\x18\x01 \x02(\t\" \n\x10PBSimpleResponse\x12\x0c\n\x04\x62oum\x18\x01 \x02(\t')




_PBSIMPLEREQUEST = _descriptor.Descriptor(
  name='PBSimpleRequest',
  full_name='PBSimpleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='youpla', full_name='PBSimpleRequest.youpla', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=57,
)


_PBSIMPLERESPONSE = _descriptor.Descriptor(
  name='PBSimpleResponse',
  full_name='PBSimpleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boum', full_name='PBSimpleResponse.boum', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['PBSimpleRequest'] = _PBSIMPLEREQUEST
DESCRIPTOR.message_types_by_name['PBSimpleResponse'] = _PBSIMPLERESPONSE

class PBSimpleRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSIMPLEREQUEST

  # @@protoc_insertion_point(class_scope:PBSimpleRequest)

class PBSimpleResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSIMPLERESPONSE

  # @@protoc_insertion_point(class_scope:PBSimpleResponse)


# @@protoc_insertion_point(module_scope)
