
#use spaces not tab !
{ 
'client':{
    'zookeeper':{
        'ip':'127.0.0.1',
        'port':'2181'
    },
    'majordaemon_url':'tcp://localhost:8081'
},
'global':{
   #Sur l'axe du temps écrire un label toutes les X mesures
   'XLABELFREQUENCY':900

}  
}
