
from distark.majordaemon.worker.processors.anotherprocessor import another_request_handler
from distark.commons.protos.generic_service_pb2 import ANOTHER_REQUEST

from distark.majordaemon.worker.processors.SimpleProcessor import simple_request_handler
from distark.commons.protos.generic_service_pb2 import SIMPLE_REQUEST

from distark.majordaemon.worker.processors.searchfoodprocessor import search_food_request_handler
from distark.commons.protos.generic_service_pb2 import SEARCH_FOOD_REQUEST
