# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objects/food.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='objects/food.proto',
  package='',
  serialized_pb='\n\x12objects/food.proto\"\x80\x01\n\x06PBFood\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03\x63\x61l\x18\x02 \x02(\x02\x12\x0b\n\x03glu\x18\x03 \x02(\x02\x12\x0b\n\x03pro\x18\x04 \x02(\x02\x12\x0b\n\x03lip\x18\x05 \x02(\x02\x12\x10\n\x08\x62\x61se_qty\x18\x06 \x02(\x05\x12\"\n\rbase_qty_unit\x18\x07 \x02(\x0e\x32\x0b.PBUnitType*\x88\x01\n\nPBUnitType\x12\x0b\n\x07UNIT_GR\x10\x01\x12\r\n\tUNIT_PART\x10\x02\x12\x0c\n\x08UNIT_POT\x10\x03\x12\x0e\n\nUNIT_UNITY\x10\x04\x12\x0e\n\nUNIT_SLICE\x10\x05\x12\x0b\n\x07UNIT_ML\x10\x06\x12\x0c\n\x08UNIT_CAN\x10\x07\x12\x15\n\x11UNIT_COFFEE_SPOON\x10\x08')

_PBUNITTYPE = _descriptor.EnumDescriptor(
  name='PBUnitType',
  full_name='PBUnitType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNIT_GR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_PART', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_POT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_UNITY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_SLICE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_ML', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_CAN', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT_COFFEE_SPOON', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=154,
  serialized_end=290,
)

PBUnitType = enum_type_wrapper.EnumTypeWrapper(_PBUNITTYPE)
UNIT_GR = 1
UNIT_PART = 2
UNIT_POT = 3
UNIT_UNITY = 4
UNIT_SLICE = 5
UNIT_ML = 6
UNIT_CAN = 7
UNIT_COFFEE_SPOON = 8



_PBFOOD = _descriptor.Descriptor(
  name='PBFood',
  full_name='PBFood',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PBFood.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cal', full_name='PBFood.cal', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glu', full_name='PBFood.glu', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pro', full_name='PBFood.pro', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lip', full_name='PBFood.lip', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base_qty', full_name='PBFood.base_qty', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base_qty_unit', full_name='PBFood.base_qty_unit', index=6,
      number=7, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=151,
)

_PBFOOD.fields_by_name['base_qty_unit'].enum_type = _PBUNITTYPE
DESCRIPTOR.message_types_by_name['PBFood'] = _PBFOOD

class PBFood(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBFOOD

  # @@protoc_insertion_point(class_scope:PBFood)


# @@protoc_insertion_point(module_scope)
